-- MySQL Script generated by MySQL Workbench
-- lun. 10 déc. 2018 13:41:41 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user_upload`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_upload` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mail_sender` CHAR(255) NOT NULL,
  `upload_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`files`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`files` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `file_url` CHAR(255) NOT NULL,
  `file_name` CHAR(255) NOT NULL,
  `file_size` VARCHAR(45) NOT NULL,
  `file_ext` VARCHAR(45) NOT NULL,
  `file_key` CHAR(255) NOT NULL,
  `user_upload_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_upload_id`),
  INDEX `fk_files_user_upload1_idx` (`user_upload_id` ASC),
  CONSTRAINT `fk_files_user_upload1`
    FOREIGN KEY (`user_upload_id`)
    REFERENCES `mydb`.`user_upload` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`user_download`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_download` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mail_receiver` CHAR(255) NOT NULL,
  `download_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`admin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`files_has_user_download`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`files_has_user_download` (
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`files_has_user_download1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`files_has_user_download1` (
  `files_id` INT NOT NULL,
  `user_download_id` INT NOT NULL,
  PRIMARY KEY (`files_id`, `user_download_id`),
  INDEX `fk_files_has_user_download1_user_download1_idx` (`user_download_id` ASC),
  INDEX `fk_files_has_user_download1_files1_idx` (`files_id` ASC),
  CONSTRAINT `fk_files_has_user_download1_files1`
    FOREIGN KEY (`files_id`)
    REFERENCES `mydb`.`files` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_files_has_user_download1_user_download1`
    FOREIGN KEY (`user_download_id`)
    REFERENCES `mydb`.`user_download` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
